version: "3.7"
services:
  node:
    image: node:alpine
    restart: always
    tty: true
    container_name: graphql
    volumes:
      - ${PWD}:/project
    links:
      - pgsql
    ports:
      - "4500:4500"
  pgsql:
    image: postgres:alpine
    restart: always
    container_name: pgsql
    extra_hosts:
      - "remote:172.17.0.1"
    ports:
      - "127.0.0.1:5432:5432"
  adminer:
    container_name: adminer
    restart: always
    image: adminer:latest
    environment:
      - ADMINER_DESIGN=pepa-linha
    links:
      - pgsql
    extra_hosts:
      - "remote:172.17.0.1"
    ports:
      - "9999:8080"
