version: "3.7"
services:
  nodejs:
    image: node:alpine
    restart: always
    tty: true
    container_name: graphql-node
    depends_on:
      - pgsql
    links:
      - pgsql
    ports:
      - "4500:4500"
    volumes:
      - ".:/home/graphql"
  pgsql:
    image: postgres:alpine
    restart: always
    container_name: pgsql
    extra_hosts:
      - "remote:172.17.0.1"
  adminer:
    container_name: adminer
    restart: always
    image: adminer:latest
    environment:
      - ADMINER_DESIGN=pepa-linha
    links:
      - pgsql
    extra_hosts:
      - "remote:172.17.0.1"
    ports:
      - "9999:8080"
