type RFQ implements Node {
  id: ID!

  "询价单所属车系"
  vehicleSeries: String

  "询价单所属车型"
  vehicleModel: String

  "询价单描述"
  description: String

  "询价单封面"
  RFQCover: String

  "发布人"
  announcer: User

  "询价单配件"
  vechicleAccessories: [Accessories!]

  "发布日期"
  announceAt: String
}

input RFQCreateInput {
  "询价单所属车系"
  vehicleSeries: String

  "询价单所属车型"
  vehicleModel: String

  "询价单配件id"
  vechicleAccessories: [ID!]

  "询价单描述"
  description: String

  "询价单图片"
  RFQImages: [String!]

  "发布人 id"
  announcerId: ID!
}

type RFQActionResult {
  id: ID
  status: Boolean
}

input RFQDeleteInput {
  id: ID!
}

type RFQConnection implements Connection {
  pageInfo: PageInfo
  edges: [RFQ!]
}

input RFQSearchInput {
  "偏离值"
  offset: Int
  "分页条数"
  limit: Int
  "创建时间排序 默认为倒叙"
  sort: SortType
}

extend type Query {
  RFQs(query: RFQSearchInput): RFQConnection
  RFQ(id: ID!): RFQ
}

extend type Mutation {
  createRFQ(createRFQInput: RFQCreateInput!): RFQActionResult
  deleteRFQ(deleteRFQInput: RFQDeleteInput!): RFQActionResult
}
