version: 2
jobs:
  build:
    docker:
      - image: node:alpine
    working_directory: ~/repo
    steps:
      - run:
          command: |
            apk add --no-cache ca-certificates
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          command: |
            yarn install
            yarn build
            mv Dockferfile dist/
            mv package.json dist/

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish docker:
    machine: true
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: dist
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t leezzxuan/gql:$CIRCLE_BRANCH dist
      - run: docker push leezzxuan/gql:$CIRCLE_TAG

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish docker:
          requires:
            - build
