"分类"
type Category {
  "分类id"
  id: ID!
  "名称"
  name: String!
  "状态"
  status: CategoryStatus!
  "标签"
  tag: String!
  "路由地址"
  route: String
  "分类图片 用作icon展示"
  image: String
  "子分类"
  children: [Category!]
}

"分类状态"
enum CategoryStatus {
  "热门"
  HOT
  "正常"
  NORMAL
}

"分类操作返回"
type CategoryResult {
  id: ID!
  status: Boolean
}

"添加分类输入"
input CategoryCreateInput {
  "名称"
  name: String!
  "状态"
  status: CategoryStatus!
  "标签"
  tag: String!
  "页面"
  route: String!
  "父级分类id 不传 默认为一级分类"
  parentId: ID
}

"删除分类输入"
input CategoryDeleteInput {
  id: ID!
}

"分类查询输入"
input CategoryQuery {
  "获取指定页面的分类"
  route: String
  "分类id 不传默认返回为一级分类"
  id: ID
}

extend type Query {
  categorys(query: CategoryQuery): [Category!]
}
extend type Mutation {
  createCategory(category: CategoryCreateInput!): CategoryResult
  deleteCategory(category: CategoryDeleteInput!): CategoryResult
}
