"商品属性"
type AttributeSpec {
  "属性ID"
  id: ID
  "属性值"
  attrValue: String
  "当前属性下的子属性"
  specs: [AttributeSpec!]
}

"商品sku"
type SKU {
  "商品sku id"
  skuId: ID
  "商品sku code 通过属性值拼接获得"
  skuCode: [String!]
  "商品sku 价格"
  skuPrice: Float
}

input GoodAttributeSearchInput {
  "商品id"
  goodId: ID!
}

input GoodAttributeCreateInput {
  "商品属性值"
  attrValue: String!
  "商品父属性"
  parentId: ID
  "商品id"
  goodId: ID!
}

type GoodAttributeActionResult {
  "属性ID"
  id: ID
  "操作回执状态"
  status: Boolean
}

extend type Query {
  goodAttribute(query: GoodAttributeSearchInput!): [AttributeSpec!]
}

extend type Mutation {
  createGoodAttribute(
    createGoodAttributeInput: GoodAttributeCreateInput!
  ): GoodAttributeActionResult
}
