scalar Date
scalar Number

type Query
type Mutation

interface Node {
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  total: Int!
}

"鉴权指令"
directive @auth(requires: Role = CUSTOMER) on OBJECT | FIELD_DEFINITION
