scalar Date

"需求帖子"
type Demand {
  "需求帖子id"
  id: ID
  "客户姓名"
  customerName: String
  "客户手机号"
  customerPhone: Int
  "车系"
  vehicleSeries: String
  "车型"
  vehicleModel: String
  "需求备注"
  mark: String
  "需求图片集合"
  images: [String!]
  "创建时间"
  createdAt: Date
}

"需求帖子列表"
type Demands {
  "需求帖子列表"
  demands: [Demand!]
  "每页数量"
  pageSize: Int
  "页数"
  page: Int
  "总页数量"
  total: Int
}

extend type Query {
  "需求贴子列表 支持车系 车型 创建事件过滤"
  demands(vehicleModel: String, vehicleSeries: String, createdAt: Date): Demands
}
