"轮播图结构"
type Banner implements Node {
  "轮播图标识"
  id: ID!
  "轮播图标题"
  title: String
  "轮播图片地址"
  path: String
  "轮播图文本内容"
  content: String
  "轮播图标签 用于区别不同页面"
  tag: String
  "banner 跳转链接"
  link: String
}

input BannerInput {
  "轮播图标题"
  title: String
  "轮播图片地址"
  path: String
  "轮播图文本内容"
  content: String
  "轮播图标签 用于区别不同页面"
  tag: String
  "banner 跳转链接"
  link: String

  "商品id"
  goodId: ID
}

"轮播查询"
input BannerQueryInput {
  tag: String!
}

input BannerUpdateInput {
  "轮播图标识"
  id: ID!
  "轮播图标题"
  title: String
  "轮播图片地址"
  path: String
  "轮播图文本内容"
  content: String
  "轮播图标签 用于区别不同页面"
  tag: String
  "banner 跳转链接"
  link: String
}

"添加/删除 轮播图结果"
type BannerActionResult {
  id: ID!
  status: Boolean!
}

extend type Query {
  "轮播图查询"
  banners(bannerQueryInput: BannerQueryInput!): [Banner!]
}

extend type Mutation {
  "添加轮播图"
  createBanner(bannerInput: BannerInput): BannerActionResult
  "删除轮播图"
  deleteBanner(id: ID!): BannerActionResult
  "修改轮播图"
  updateBanner(bannerUpdateInput: BannerUpdateInput!): BannerActionResult
}
