"商品"
type Good {
  "商品id"
  id: ID!
  "商品名称"
  name: String  @auth
  "商品图片 默认第一张为封面"
  images: [String!]
  "商品描述"
  description: String
  "商户id"
  merchantId: Int
  "商品状态"
  status: GOODSTATUS
}

"商品状态枚举"
enum GOODSTATUS {
  "在线"
  ONLINE
  "下线"
  OFFLINE
}

"商品列表"
type Goods {
  "商品列表"
  goods: [Good!]
  "每页数量"
  pageSize: Int
  "页数"
  page: Int
  "总页数量"
  total: Int
}

extend type Query {
  "商品查询 可通过商品id、名称进行查询"
  good(id: ID!, name: String): Good
  "商品列表查询 可通过页码 页数进行分页处理"
  goodList(page: Int, pageSize: Int): Goods
}
